version: "3.7"
services:
  elasticsearch:
    image: "elastic"
    container_name: "elasticsearch_local"
    enivronment:
      - xpack.security.enabled=false
  kibana:
    image: "kibana"
    container_name: "ki"
    depends_on:
      - elasticsearch
  searcher_pro:
    build: .
    container_name: "searcher_project"
    depends_on:
      - elasticsearch
